version: '3.8'
services:
  # App
  app:
    image: 'rest-currency-convert:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db

  # Database Service (Postgres)
  db:
    image: postgres:12
    container_name: postgres-db
    restart: always

    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: playground