version: '3.8'
services:
  # App
  app:
    image: rest-currency-convert:latest
    container_name: currency-convert-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    depends_on:
      - db

  # Database Service (Postgres)
  db:
    image: postgres:12
    container_name: postgres-db
    ports:
      - "5432:5432"
    restart: always

    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: playground