spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/playground?schema=currency_exchanges
    username: root
    password: root

  application:
    name: rest-currency-convert

  flyway:
    url: jdbc:postgresql://localhost:5432/playground
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    baseline-on-migrate: true

server:
  port: 8080

logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG

springdoc:
  version: 1
  use-root-path: true
  swagger-ui:
    use-root-path: true