spring:
  r2dbc:
    #If you choose to run locally without docker, then change 'db' to 'localhost'
    url: r2dbc:postgresql://db:5432/playground?schema=currency_exchanges
    username: root
    password: root

  application:
    name: rest-currency-convert

  flyway:
    #If you choose to run locally without docker, then change 'db' to 'localhost'
    url: jdbc:postgresql://db:5432/playground
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    baseline-on-migrate: true

server:
  port: 8088

logging:
  level:
    org.springframework.data.r2dbc: debug

springdoc:
  version: 1.0
  use-root-path: true
  swagger-ui:
    use-root-path: true